### ISSUE TITLE
Manual: 300mm bed frame spacing.

### ISSUE THREAD

**Issue by atoomnetmarc** [VoronDesign/Voron-Trident#133] opened 2023-10-10 18:07 UTC
Hi,

I am assembling a Trident 300, is it possible that the suggested 175mm spacing for the F-extrusion should be 25mm more when assembling a Trident 300?

![afbeelding](https://github.com/VoronDesign/Voron-Trident/assets/48124268/e3071ed5-ff5a-4dd3-9cc7-118326d3ad5d)

Just like this:

![afbeelding](https://github.com/VoronDesign/Voron-Trident/assets/48124268/aedea0ce-430c-4a41-bbd2-67b2715297a4)

**Comment by nemgrea** [comment] 2024-02-09 00:56
Duplicate of #77

**Closed by nemgrea** 2024-02-09 00:56 UTC
Labels: Manual
